// pages/politica-de-privacidade.vue
<template>
  <div class="pb-16 pt-8 sm:pt-12">
    <div class="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
      <p class="mb-6">
        <NuxtLink
          to="/"
          class="text-sm font-medium text-primary hover:underline"
        >
          ← Voltar ao início
        </NuxtLink>
      </p>
      <article class="rounded-2xl bg-white/80 p-6 shadow-sm ring-1 ring-gray-900/5 sm:p-10">
        <header class="mb-8 border-b border-gray-200 pb-8">
          <h1 class="text-3xl font-medium tracking-tight text-gray-900">
            Política de privacidade do aplicativo OnlyWine
          </h1>
          <p class="mt-2 text-sm text-gray-500">
            Última atualização: 23 de abril de 2026
          </p>
        </header>

        <div class="prose prose-gray max-w-none space-y-6 text-gray-700">
          <section>
            <h2 class="text-lg font-semibold text-gray-900">
              1. Introdução
            </h2>
            <p class="mt-2 text-base leading-relaxed">
              A OnlyWine respeita a sua privacidade. Esta Política descreve como
              coletamos, usamos, armazenamos e protegemos dados pessoais quando
              você utiliza o aplicativo OnlyWine (“App”) em dispositivos móveis.
            </p>
          </section>

          <section>
            <h2 class="text-lg font-semibold text-gray-900">
              2. Controlador dos dados
            </h2>
            <p class="mt-2 text-base leading-relaxed">
              O responsável pelo tratamento dos dados pessoais coletados por meio
              do App é a OnlyWine, conforme identificada nas lojas de aplicativos
              e nos canais oficiais de contato.
            </p>
          </section>

          <section>
            <h2 class="text-lg font-semibold text-gray-900">
              3. Dados que podemos coletar
            </h2>
            <p class="mt-2 text-base leading-relaxed">
              Dependendo de como você usa o App e das funcionalidades
              disponíveis, podemos tratar categorias como:
            </p>
            <ul class="mt-3 list-disc space-y-2 pl-5 text-base leading-relaxed">
              <li>
                dados de cadastro e perfil (por exemplo, nome, e-mail ou
                identificador de conta);
              </li>
              <li>
                dados de uso do App (como interações, preferências de vinhos e
                eventos de analytics de forma agregada ou pseudonimizada);
              </li>
              <li>
                dados técnicos do dispositivo e da conexão (como modelo do
                aparelho, sistema operacional, idioma e identificadores
                anônimos necessários para notificações ou diagnóstico de erros).
              </li>
            </ul>
          </section>

          <section>
            <h2 class="text-lg font-semibold text-gray-900">
              4. Finalidades do tratamento
            </h2>
            <p class="mt-2 text-base leading-relaxed">
              Utilizamos os dados para prestar e melhorar o App, personalizar
              recomendações quando aplicável, garantir segurança, cumprir
              obrigações legais, comunicar atualizações relevantes e, mediante
              base legal adequada, realizar estatísticas e aprimoramento do
              produto.
            </p>
          </section>

          <section>
            <h2 class="text-lg font-semibold text-gray-900">
              5. Compartilhamento
            </h2>
            <p class="mt-2 text-base leading-relaxed">
              Podemos compartilhar dados com prestadores de serviços que nos
              auxiliam na hospedagem, analytics, notificações push ou suporte,
              sempre mediante contratos e medidas de segurança compatíveis com a
              legislação aplicável. Não vendemos seus dados pessoais.
            </p>
          </section>

          <section>
            <h2 class="text-lg font-semibold text-gray-900">
              6. Armazenamento e segurança
            </h2>
            <p class="mt-2 text-base leading-relaxed">
              Adotamos práticas razoáveis de segurança da informação para
              proteger os dados contra acesso não autorizado, perda ou alteração.
              Nenhum sistema é totalmente isento de riscos; em caso de incidente
              relevante, buscaremos agir conforme a lei.
            </p>
          </section>

          <section>
            <h2 class="text-lg font-semibold text-gray-900">
              7. Retenção
            </h2>
            <p class="mt-2 text-base leading-relaxed">
              Mantemos os dados pelo tempo necessário para cumprir as
              finalidades descritas, respeitar prazos legais e preservar direitos
              em eventual controvérsia.
            </p>
          </section>

          <section>
            <h2 class="text-lg font-semibold text-gray-900">
              8. Seus direitos (LGPD)
            </h2>
            <p class="mt-2 text-base leading-relaxed">
              Nos termos da Lei nº 13.709/2018 (LGPD), você pode solicitar
              confirmação de tratamento, acesso, correção, anonimização,
              portabilidade, eliminação de dados desnecessários, informação sobre
              compartilhamentos e revogação de consentimento quando o
              tratamento for baseado nele. O exercício pode ser feito pelos
              canais indicados abaixo.
            </p>
          </section>

          <section>
            <h2 class="text-lg font-semibold text-gray-900">
              9. Crianças e adolescentes
            </h2>
            <p class="mt-2 text-base leading-relaxed">
              O App não se destina a menores de 18 anos. Se tomarmos ciência de
              dados coletados inadvertidamente de menores sem consentimento
              legal adequado, adotaremos medidas para eliminá-los.
            </p>
          </section>

          <section>
            <h2 class="text-lg font-semibold text-gray-900">
              10. Alterações desta política
            </h2>
            <p class="mt-2 text-base leading-relaxed">
              Podemos atualizar este texto para refletir mudanças no App ou na
              legislação. A data da última versão aparecerá no topo desta página;
              alterações relevantes podem ser comunicadas também pelo App ou por
              e-mail, quando aplicável.
            </p>
          </section>

          <section>
            <h2 class="text-lg font-semibold text-gray-900">
              11. Contato
            </h2>
            <p class="mt-2 text-base leading-relaxed">
              Para dúvidas ou solicitações relacionadas a privacidade e
              proteção de dados, envie um e-mail para
              <a
                href="mailto:contact@onlywine.app"
                class="font-medium text-primary hover:underline"
              >contact@onlywine.app</a>
              ou acesse
              <a
                href="https://onlywine.app"
                class="font-medium text-primary hover:underline"
                rel="noopener noreferrer"
                target="_blank"
              >onlywine.app</a>.
              Também pode utilizar os canais oficiais na App Store e no Google Play.
            </p>
          </section>
        </div>
      </article>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  name: 'PoliticaPrivacidadePage',
  head() {
    return {
      title: 'OnlyWine — Política de privacidade',
      meta: [
        {
          hid: 'description',
          name: 'description',
          content:
            'Política de privacidade do aplicativo OnlyWine: coleta, uso e proteção dos seus dados.',
        },
      ],
    }
  },
})
</script>

// app/politica-de-privacidade/page.tsx
import type { Metadata } from "next";

import { LegalPage, LegalSection } from "@/components/legal-page";
import { addressLine, company } from "@/lib/site";

export const metadata: Metadata = {
  title: "Política de privacidade",
  description:
    "Política de privacidade do aplicativo OnlyWine: quais dados são coletados, para quê, com quem são compartilhados e quais são os seus direitos sob a LGPD.",
  alternates: { canonical: "/politica-de-privacidade" },
};

export default function PoliticaDePrivacidade() {
  return (
    <LegalPage
      title="Política de privacidade do aplicativo OnlyWine"
      updatedAt="23 de abril de 2026"
    >
      <LegalSection number={1} title="Introdução">
        <p>
          A OnlyWine respeita a sua privacidade. Esta Política descreve como
          coletamos, usamos, armazenamos e protegemos dados pessoais quando você
          utiliza o aplicativo OnlyWine (“App”) em dispositivos móveis.
        </p>
      </LegalSection>

      {/*
        Identificação completa do controlador. O texto anterior dizia apenas
        "a OnlyWine, conforme identificada nas lojas de aplicativos" — vago
        demais para o art. 9º da LGPD e sem nenhum valor para a Apple confirmar
        que o domínio pertence à organização inscrita.
      */}
      <LegalSection number={2} title="Controlador dos dados">
        <p>
          O responsável pelo tratamento dos dados pessoais coletados por meio do
          App é:
        </p>
        <ul>
          <li>
            <strong>Razão social:</strong> {company.legalName}
          </li>
          <li>
            <strong>CNPJ:</strong> {company.cnpj}
          </li>
          <li>
            <strong>Endereço:</strong> {addressLine}
          </li>
          <li>
            <strong>E-mail para assuntos de privacidade:</strong>{" "}
            <a href={`mailto:${company.email}`}>{company.email}</a>
          </li>
        </ul>
      </LegalSection>

      <LegalSection number={3} title="Dados que podemos coletar">
        <p>
          Dependendo de como você usa o App e das funcionalidades disponíveis,
          podemos tratar categorias como:
        </p>
        <ul>
          <li>
            dados de cadastro e perfil (por exemplo, nome, e-mail, telefone,
            país, data de nascimento e foto);
          </li>
          <li>endereços de entrega salvos e histórico de pedidos;</li>
          <li>
            dados de uso do App (como interações, vinhos favoritos, preferências
            e eventos de analytics de forma agregada ou pseudonimizada);
          </li>
          <li>
            dados técnicos do dispositivo e da conexão (como modelo do aparelho,
            sistema operacional, idioma e identificadores anônimos necessários
            para notificações ou diagnóstico de erros).
          </li>
        </ul>
      </LegalSection>

      <LegalSection number={4} title="Finalidades do tratamento">
        <p>
          Utilizamos os dados para prestar e melhorar o App, processar pedidos e
          entregas, personalizar recomendações quando aplicável, garantir
          segurança, cumprir obrigações legais, comunicar atualizações relevantes
          e, mediante base legal adequada, realizar estatísticas e aprimoramento
          do produto.
        </p>
      </LegalSection>

      <LegalSection number={5} title="Compartilhamento">
        <p>
          Podemos compartilhar dados com prestadores de serviços que nos auxiliam
          na hospedagem, analytics, notificações push, meios de pagamento,
          logística de entrega ou suporte, sempre mediante contratos e medidas de
          segurança compatíveis com a legislação aplicável.{" "}
          <strong>Não vendemos seus dados pessoais.</strong>
        </p>
      </LegalSection>

      <LegalSection number={6} title="Armazenamento e segurança">
        <p>
          Adotamos práticas razoáveis de segurança da informação para proteger os
          dados contra acesso não autorizado, perda ou alteração. Nenhum sistema é
          totalmente isento de riscos; em caso de incidente relevante, buscaremos
          agir conforme a lei.
        </p>
      </LegalSection>

      <LegalSection number={7} title="Retenção">
        <p>
          Mantemos os dados pelo tempo necessário para cumprir as finalidades
          descritas, respeitar prazos legais e preservar direitos em eventual
          controvérsia.
        </p>
      </LegalSection>

      <LegalSection number={8} title="Seus direitos (LGPD)">
        <p>
          Nos termos da Lei nº 13.709/2018 (LGPD), você pode solicitar confirmação
          de tratamento, acesso, correção, anonimização, portabilidade, eliminação
          de dados desnecessários, informação sobre compartilhamentos e revogação
          de consentimento quando o tratamento for baseado nele. O exercício pode
          ser feito pelos canais indicados abaixo.
        </p>
        <p>
          Para excluir sua conta e todos os dados associados, você também pode
          usar a página de{" "}
          <a href="/excluir-conta">exclusão de conta</a>, que faz a remoção de
          forma imediata e permanente.
        </p>
      </LegalSection>

      <LegalSection number={9} title="Crianças e adolescentes">
        <p>
          O App não se destina a menores de 18 anos. Se tomarmos ciência de dados
          coletados inadvertidamente de menores sem consentimento legal adequado,
          adotaremos medidas para eliminá-los.
        </p>
      </LegalSection>

      <LegalSection number={10} title="Alterações desta política">
        <p>
          Podemos atualizar este texto para refletir mudanças no App ou na
          legislação. A data da última versão aparecerá no topo desta página;
          alterações relevantes podem ser comunicadas também pelo App ou por
          e-mail, quando aplicável.
        </p>
      </LegalSection>

      <LegalSection number={11} title="Contato">
        <p>
          Para dúvidas ou solicitações relacionadas a privacidade e proteção de
          dados, envie um e-mail para{" "}
          <a href={`mailto:${company.email}`}>{company.email}</a> ou use o{" "}
          <a href="/contato">formulário de contato</a>. Respondemos em dias úteis.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
